### PR TITLE
Open mode

### PR DESCRIPTION
**Pull request by RebelusQuo**
I cleaned the whitespace style and added directly to master. I didn't like moving css and html files to sub directories since it introduced unnecessary parent folder paths.

I'd like to hear what @crossproduct42 thinks of this before rebasing into master. @gunrugger, let me know if I got anything wrong in these commits.

### CODE REVIEW

**Comment by RebelusQuo** [comment]
I happened to close this by accident when changing my remotes.

**Review by crossproduct42 — CHANGES_REQUESTED** [review]
See the Issue I posted regarding logic updates for Open Mode in chests.js
If I'm not too tired after work, I can go down the list and make a list of which ones need to be updated.

**Comment by rogernorling** [comment]
Last commit is Work In Progress, please review the chest state logic.

**Comment by rogernorling** [comment]
Force pushed a8bbbf2. Updated Hyrule Castle locations.

**Pull request merged**
