### PR TITLE
Right click functionality

### PR DESCRIPTION
**Pull request by sillypears**
Added the ability to use right click on the tracker items.

Toggleable cells will do what they always did. 
Counted cells will reverse cell order (can clear all dungeon chests with a single right click vs X clicks)

Also my first time with React.JS so if there are better ways or if I did extra work, please let me know and I will look into fixing these things.

### CODE REVIEW

**Comment by RebelusQuo** [comment]
This looks good. However, it's considered bad practice to override default browser behavior more than necessary so I will not include c09785a and 91f1a8c, and I will change some variable names as I merge this. It will be merged as soon as we get keysanity support in, which should be very soon now.

**Comment by sillypears** [comment]
Thanks, and all that makes sense. These were just personal changes I made to the tracker when I was using it and figured they could be useful to others.

**Comment by RebelusQuo** [comment]
@sillypears By pushing on master which is the branch you used for this pull request you are in effect changing this pull request. A better method is to develop on a feature branch and use that for a pull request.

Since you used master which is now changing, and that we will be making many changes to our master, I will close this.

**Comment by sillypears** [comment]
I forgot that I had done this on master. I have updated my fork of this so that master is back in line with this and put my features on a feature branch. Sorry about that. I can PR it again as with the feature branch if the functionality would be considered useful, so going forward it can be merged. Also any personal changes I've also added as its own branch to keep my personal prefs out of the actual feature updates I have added. 

Again, sorry about pushing to master.

**Pull request closed without merging**
